FROM amazoncorretto:11-alpine

WORKDIR /app

ENV PROFILES=dev

ARG ORIGINAL_JAR_FILE=./build/libs/member-service-1.0.0.jar

COPY ${ORIGINAL_JAR_FILE} member-service.jar

CMD ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/member-service.jar"]
