-- H2 2.1.214;
SET
DB_CLOSE_DELAY -1;
;             
CREATE
USER IF NOT EXISTS "SA" SALT '045126beafa8a0ea' HASH '6d09a520b82fd203354f6fea2fcac3e2bc801bc2c166a7c91e75a22d53376800' ADMIN;
CREATE
MEMORY TABLE "PUBLIC"."delivery_address"(
    "delivery_address_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "delivery_address_detail" CHARACTER VARYING(255) NOT NULL,
    "delivery_address_is_default" BOOLEAN NOT NULL,
    "delivery_address_recipient_email" CHARACTER VARYING(255),
    "delivery_address_recipient_name" CHARACTER VARYING(255) NOT NULL,
    "delivery_address_recipient_phone_number" CHARACTER VARYING(255) NOT NULL,
    "delivery_address_request" CHARACTER VARYING(255),
    "delivery_address_road_name" CHARACTER VARYING(255) NOT NULL,
    "delivery_address_zip_code" CHARACTER VARYING(255) NOT NULL,
    "member_id" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."delivery_address"
    ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY ("delivery_address_id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.delivery_address;        
CREATE
MEMORY TABLE "PUBLIC"."likes"(
    "project_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "member_id" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."likes"
    ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY ("member_id", "project_id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.likes;   
CREATE
MEMORY TABLE "PUBLIC"."member"(
    "member_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 2) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "member_email" CHARACTER VARYING(255) NOT NULL,
    "member_is_activate" BOOLEAN NOT NULL,
    "member_name" CHARACTER VARYING(10) NOT NULL,
    "member_password" CHARACTER VARYING(255) NOT NULL,
    "member_phone_number" CHARACTER VARYING(255) NOT NULL,
    "member_point" BIGINT NOT NULL,
    "member_privacy_agreement" BOOLEAN NOT NULL,
    "member_profile_image_url" CHARACTER VARYING(255) NOT NULL,
    "member_role" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "PUBLIC"."member"
    ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY ("member_id");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.member;  
INSERT INTO "PUBLIC"."member"
VALUES (1, NULL, NULL, 'test@naver.com', TRUE, U&'\c774\c6b0\c5fd',
        '$2y$10$UMEd9dWb.nIWQp84umaeiuhAilkHXS/04MmCKijGJ2uH8iuPcquQG', '01000000000', 0, TRUE,
        'https://picsum.photos/200', 'ROLE_USER');
CREATE
MEMORY TABLE "PUBLIC"."membership"(
    "membership_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "member_id" BIGINT NOT NULL,
    "membership_policy_id" BIGINT NOT NULL,
    "membership_status" BOOLEAN NOT NULL,
    "membership_subscription_created_at" TIMESTAMP NOT NULL,
    "membership_subscription_expired_at" TIMESTAMP NOT NULL
);
ALTER TABLE "PUBLIC"."membership"
    ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B0" PRIMARY KEY ("membership_id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.membership;              
CREATE
MEMORY TABLE "PUBLIC"."membership_policy"(
    "membership_policy_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "membership_policy_discount_rate" INTEGER NOT NULL,
    "membership_policy_grade" CHARACTER VARYING(255) NOT NULL,
    "membership_policy_point_accumulation_rate" INTEGER NOT NULL,
    "membership_policy_subscription_fee" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."membership_policy"
    ADD CONSTRAINT "PUBLIC"."CONSTRAINT_61" PRIMARY KEY ("membership_policy_id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.membership_policy;       
CREATE
MEMORY TABLE "PUBLIC"."membership_subscription"(
    "membership_subscription_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "created_at" TIMESTAMP,
    "updated_at" TIMESTAMP,
    "membership_id" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."membership_subscription"
    ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY ("membership_subscription_id");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.membership_subscription; 
ALTER TABLE "PUBLIC"."member"
    ADD CONSTRAINT "PUBLIC"."UK_3orqjaukiw2b73e2gw8rer4rq" UNIQUE ("member_email");
ALTER TABLE "PUBLIC"."likes"
    ADD CONSTRAINT "PUBLIC"."FKa4vkf1skcfu5r6o5gfb5jf295" FOREIGN KEY ("member_id") REFERENCES "PUBLIC"."member" ("member_id") NOCHECK;


-- INSERT INTO "member"
-- ("member_email", "member_is_activate", "member_name", "member_password", "member_phone_number",
--  "member_point", "member_privacy_agreement", "member_profile_image_url", "member_role")
-- VALUES ('test@naver.com', TRUE, 'ddddd', 'dddddddd', '01000000000', 0, TRUE,
--         'https://picsum.photos/200', 'ROLE_USER');
